project_structure:
    build: build
    contracts: contracts
    interfaces: interfaces
    reports: reports
    scripts: scripts
    tests: tests

networks:
    default: short-lived
    short-lived:
        gas_limit: 12000000
        gas_price: 0
        reverting_tx_gas_limit: 12000000
        default_contract_owner: true
        cmd_settings: 
            gas_limit: 12000000
            mnemonic: brownie
    development:
        gas_limit: 12000000
        gas_price: 0
        reverting_tx_gas_limit: 12000000
        default_contract_owner: true
        cmd_settings: 
            gas_limit: 12000000
            mneumonic: brownie
    live:
        gas_limit: auto
        gas_price: auto
        reverting_tx_gas_limit: false
        default_contract_owner: false

compiler:
    evm_version: null
    solc:
        version: 0.5.7
        optimizer:
            enabled: true
            runs: 200
        remappings: null

console:
    show_colors: true
    color_style: monokai
    auto_suggest: true
    completions: true

reports:
    exclude_paths: null
    exclude_contracts: null

hypothesis:
    deadline: null
    max_examples: 50
    report_multiple_bugs: False
    stateful_step_count: 10

autofetch_sources: false
dependencies: null
dev_deployment_artifacts: false
